version: '3.9'

networks:
    jenkins:
    frontend:
        driver: bridge
    backend:
        driver: bridge

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        restart: always
        networks:
            - frontend
            - backend
            - jenkins
        ports:
            - 8080:80
        environment:
            NGINX_PORT: 80
            NGINX_HOST: taoqn.vn

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        command: redis-server --appendonly yes --requirepass redis
        volumes:
            - ./redis:/data
        networks:
            - frontend
            - backend
        networks:
            frontend:
                aliases:
                    - session
            backend:
                aliases:
                    - database

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        networks:
            - backend
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678x@X

    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: always
        networks:
            - backend
        volumes:
            - ./postgres:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: 12345678x@X

    jenkins:
        container_name: jenkins
        build:
            context: ./jenkins
        networks:
            - jenkins
        ports:
            - 8555:8080
            - 50000:50000
        volumes:
            - ./jenkins/data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
